### ISSUE TITLE
Muchos cambios en el código despues de la versión 1.03

### ISSUE THREAD

**Issue by MarceloPedra** [open-pay/openpay-woocommerce#10]
Estimados, desde hace un año que venía trabajando con la versión 1.03 hasta que ahora noté algunos problemas con WooCommerce 2.5 y veo que el plugin ya figura como "old-plugin". Y ahora lo tienen segmentado en 3 variantes para descargar: cards, spei, y stores.
Quería saber si son todas estables para un entorno de producción.
Muchas gracias.

**Comment by fedebalderas** [comment]
Que tal @MarceloPedra, pues ya hay comercios utilizandolo y hasta ahorita pareciera no haber problemas. En caso de que se presentará algo, le estamos dando prioridad a la resolución de problemas en plugins.

Saludos!
