### ISSUE TITLE
¿No hay más código de verificación en la nueva versión?

### ISSUE THREAD

**Issue by MarceloPedra** [open-pay/openpay-woocommerce#11]
Hola estimados que tal. Quería preguntar cómo es la verificación del webhook desde https://dashboard.openpay.mx/settings con el nuevo plugin, específicamente si sólo quiero activar el plugin openpay-cards. Desde el dashboard de openpay me dice que no se puede conectar a la URL de retorno, http://midominio/?wc-api=wc_openpay. 

Pero sin embargo si instalo la versión vieja del plugin, la validación funciona bien, me genera el código de validación para el dashboard. Acaso necesito tener activa la versión vieja Y la nueva? Porque en los plugins nuevos no tenemos los campos de datos para la validación como en el viejo. ¿Me estoy salteando algún paso?

Espero su respuesta. Saludos

**Comment by fedebalderas** [comment]
Que tal @MarceloPedra , la nueva versión del plugin tiene automatizada esta parte del código de verificación del webhook, por lo tanto ya no devuelve el código para que lo hagas manualmente.
Si por alguna razón no se esta creando, podrías revisar tu log de Openpay para ver cual es el problema de favor. Esta sección de encuentra al final del menú lateral izquierdo del dashboard de Openpay.

Quedo en espera de tus comentarios.

**Comment by fedebalderas** [comment]
@MarceloPedra te comento, el módulo de pago con tarjetas no crea un webhook, este es creado únicamente con los módulos de SPEI y de Tiendas, que son los que requieren de la notificación de pago después del checkout. Como el pago con tarjeta es inmediato el webhook no es necesario por eso no se esta creando.

Cualquier duda me dices.


Saludos!

**Comment by MarceloPedra** [comment]
Hola Fede ok, Pero entonces si no es necesario un webhook para el modulo de tarjetas, como se entera WooCommerce de que el pago fue exitoso?

**Comment by MarceloPedra** [comment]
Entonces en el dashboard de openpay.mx puedo borrar el webhook viejo sin problemas?

**Comment by fedebalderas** [comment]
Cuando se hace la petición del cargo con tarjeta, Openpay regresa una respuesta del cargo exitoso o fallido, por eso no se requiere del webhook.

Y en efecto, puedes borrar el webhook del dashboard. Al momento en que requieras instalar alguno de los otros 2 módulos, el webhook será creado automáticamente y verificado.

Saludos!
