### ISSUE TITLE
Estatus de la orden no se actualiza

### ISSUE THREAD

**Issue by Nodws** [open-pay/openpay-woocommerce#12]
El estatus permanece en "Procesando", (tarjeta en sandbox)
pero en la plataforma de Openpay dice que la compra fue completada

![image](https://cloud.githubusercontent.com/assets/3076134/18331652/cfd6b092-751d-11e6-8f68-b62cc42eaaa3.png)

**Comment by fedebalderas** [comment]
Que tal @Nodws el estatus "Procesando" indica que el pago ya fue recibido, sin embargo como esta diseñado WooCommerce ellos toman el estatus "Completado" como si tu ya hubieras enviado y procesado el pedido a tu cliente. 

En caso de que vendas artículos virtuales por ahí hay plugins que te cambian el estatus automáticamente a "Completado" ya que no hay envío de por medio, como el siguiente:
https://wordpress.org/plugins/woocommerce-autocomplete-order/

Te dejo una URL que te dejará más claro los estatus que maneja  WooCommerce:
https://docs.woocommerce.com/document/managing-orders/

Saludos!
