### ISSUE TITLE
Cual es la versión más vieja de WooCommerce que soportan?

### ISSUE THREAD

**Issue by MarceloPedra** [open-pay/openpay-woocommerce#13]
En una tienda tenemos WooCommerce 2.5.5 sobre WordPress 4.4.5 y todo corriendo bajo PHP 5.6.27, y aún así cuando uno carga los datos de la tarjeta para pagar y toca el botón para realizar el pedido, simplemente no pasa nada, como si no hubieras hecho click.

¿Alguna idea?
Gracias!

**Comment by MarceloPedra** [comment]
Agrego: revisando la consola encuentro este mensaje:

Failed to load resource: the server responded with a status of 401 (No Autorizado)
https://api.openpay.mx/v1/mupn4ftents38rjfastn/tokens

Los tokens de producción están correctamente cargados. Puede faltar algo más?

**Comment by fedebalderas** [comment]
Que tal @MarceloPedra, sería bueno que revisaras la consola de tu navegador solo para descartar que no este tronando algún JS del plugin de Openpay, de algún otro plugin o de alguno mismo de WooCommerce.

También sería oportuno si revisaras el log en tu dashboard de sandbox de Openpay para identificar cual es el error puntualmente.

Checalo y nos cuentas por favor.


Saludos!

**Comment by alexreys** [comment]
Hola Fede,

Tengo Wordpress Versión 4.6.1, woocommerce Versión 2.6.7

Tengo instalado el módulo de Openpay, cuando hago el pago con tarjeta en modo sandbox, me arroja un mensaje **Internal Server Error**  . Si me llega el email de confirmación de pedido y se agrega el pedido al administrador de Woocommerce.

Ya desactive la mayoría de plugins para ver que no estuvieran causando conflicto los Js pero me sigue marcando el error.

Ya revise la consola  y me marca un error en el jquery.js en la linea 2740

**g = c ? c.getPropertyValue(b) || c[b] : void 0,**

Que podrá ser? alguna idea?

Gracias!

**Comment by fedebalderas** [comment]
@alexreys Tendrás tu plataforma en línea como para darle un vistazo a todo el flujo? o estas en ambiente local? O si pudieras adjuntar una imagen del pantallazo del error porfa, también si pudieras checar el log de Openpay en el dashboard de sandbox para ver como llega la petición y que regresa, como ves?

Saludos!

**Comment by alexreys** [comment]
@fedebalderas Lo estaba corriendo local, y lo puse en línea para ver si pudiera corregir el error. 

Ya revise el log en el dashboard de Openpay y los estados de todas las transacciones son **201 Created y 200 Ok**

Anexo la imagen.. ahi viene la url

<img width="1680" alt="screen shot 2016-11-09 at 5 47 40 pm" src="https://cloud.githubusercontent.com/assets/23367539/20159211/db056d88-a6a4-11e6-93e4-430087636a68.png">

**Comment by fedebalderas** [comment]
@alexreys Podrías poner la plataforma en modo de debug para ver cual es el error que regresa el servidor porfa.

![screen shot 2016-11-09 at 7 18 57 pm](https://cloud.githubusercontent.com/assets/5208431/20161024/6945c564-a6b1-11e6-9406-249fa3c4e62e.png)

**Comment by alexreys** [comment]
Listo ya esta en Modo Debug

*--*
*Alex Reyes*
movil. 818 088 8979
office. (81) 19 33 88 44

**Comment by fedebalderas** [comment]
@alexreys pregunta... tienes habilitada la opción de mese sin intereses en el backoffice? 

Saludos!

**Comment by alexreys** [comment]
@fedebalderas No tengo habilitada la opción.. te adjunto la imagen Gracias!
<img width="1680" alt="screen shot 2016-11-11 at 11 59 33 am" src="https://cloud.githubusercontent.com/assets/23367539/20224898/67dcacfa-a806-11e6-96f7-430b1e9b6605.png">

**Comment by fedebalderas** [comment]
@alexreys Una disculpa por el tiempo de respuesta... Es que pareciera que siempre esperas que vengan los meses sin intereses y no es así.. esta en función de si cumple con el monto mínimo o si tienes habilitada la opción.

Agrega estas líneas desde la 286 (de hecho así viene en el plugin, no se si alguien te las cambio o tu las cambiaste).

`$interest_free = null;
        
        if(isset($_POST['openpay_month_interest_free'])){
            $interest_free = $_POST['openpay_month_interest_free'];
        }`

Me avisas como te fue??

**Comment by alexreys** [comment]
@fedebalderas  Hice los cambios pero me da este error. Aunque este error me daba antes de hacer el cambio.

SyntaxError: Unexpected token < in JSON at position 0

La línea que me dices que modifique así viene del plugin que descargue de aquí. Es muy raro en otras instalaciones de WP si me funciona.

**Comment by fedebalderas** [comment]
Ummm cierto... No se ha subdio ese fix que te menciono, pero vaya es el único cambio diferente. Por lo que mencionas creo que tienes otras instalaciones funcionando... no se si algún plugin que tengas diferentes a las otras le este metiendo ruido.
