### ISSUE TITLE
Errores no se muestran en el Frontend

### ISSUE THREAD

**Issue by didi3r** [open-pay/openpay-woocommerce#15]
En el formulario para Finalizar la Compra al ingresar los datos de la tarjeta (En modo pruebas) para procesar el pago. Si el número de la tarjeta es inválido, o si el CVC es inválido, o si la fecha de expiración es inválida, no se muestra ningún mensaje para alertar al comprador.

Abriendo la consola veo que si hay respuesta desde la API, por ejemplo:

https://sandbox-api.openpay.mx/v1/XXXXXXXXX/tokens - 400 Peticion incorrecta
```
{
    "category": "request",
    "description": "The expiration date has already passed",
    "http_code": 400,
    "error_code": 2005,
    "request_id": "709fa59e-02b1-422b-8e05-80c0ee4e47de"
}
```

Pero no hay feedback para el usuario de lo que esta pasando.

Saludos

**Comment by fedebalderas** [comment]
Que tal @didi3r,
El error es mostrado por el plugin, no sé si estes utilizando algún template en particular y este le meta ruido (se sobre ponga al mensaje de error o algo así)

Te adjunto una imagen de una prueba que recién acabo de hacer.

![pago openpay](https://cloud.githubusercontent.com/assets/5208431/25976417/6e6847fc-367a-11e7-87c2-9b5c97adfb62.png)

El error se pinta inclusive sobre un elemento con una clase propia de WooCommerce (.woocommerce-error)

Revísalo y nos comentas.

Saludos!

**Comment by didi3r** [comment]
Encontré el bug. El markup que general el plugin es el siguiente:

```
<li class="wc_payment_method payment_method_openpay_cards">
	<input id="payment_method_openpay_cards" type="radio" class="input-radio" name="payment_method" value="openpay_cards" checked="checked" data-order_button_text="">

	<label for="payment_method_openpay_cards">
		Pago con tarjeta de crédito o débito 	</label>
			<div class="payment_box payment_method_openpay_cards">
			<style>
    .form-row{
        margin: 0 0 6px !important;
        padding: 3px !important;
    }
    
    .form-row select{
        width: 100% !important;
    }
    
    
    .openpay-total{
        font-size: 2em;
        font-weight: bold;        
    }
</style>

<div style="overflow: hidden;">
    <div style="overflow: hidden;">
        <div style="width: 35%; float: left;">
            <h5>Tarjetas de crédito</h5>	
            <img alt="" src="http://dev.bioleafy.com/wp-content/plugins/openpay-cards//assets/images/credit_cards.png">	
        </div>
        <div style="width: 65%; float: left;">
            <h5>Tarjetas de débito</h5>	
            <img alt="" src="http://dev.bioleafy.com/wp-content/plugins/openpay-cards//assets/images/debit_cards.png">	
        </div>
    </div>	
    <div style="height: 1px; clear: both; border-bottom: 1px solid #CCC; margin: 10px 0 10px 0;"></div>
<!--	<span class='payment-errors required'></span>-->
            <p>SANDBOX MODE ENABLED. In test mode, you can use the card number 4111111111111111 with any CVC and a valid expiration date.</p>
        <div class="form-row form-row-wide woocommerce-validated">
        <label for="openpay-holder-name">Nombre del tarjetahabiente <span class="required">*</span></label>
        <input id="openpay-holder-name" style="font-size: 1.5em; padding: 8px;" class="input-text" type="text" autocomplete="off" placeholder="Nombre del tarjetahabiente" data-openpay-card="holder_name">
    </div>	
    <div class="form-row form-row-wide woocommerce-validated">
        <label for="openpay-card-number">Número de tarjeta <span class="required">*</span></label>
        <input id="openpay-card-number" class="input-text wc-credit-card-form-card-number" type="text" maxlength="20" autocomplete="off" placeholder="•••• •••• •••• ••••" data-openpay-card="card_number">
    </div>
    <div class="form-row form-row-first woocommerce-validated">
        <label for="openpay-card-expiry">Expira (MM/YY) <span class="required">*</span></label>
        <input id="openpay-card-expiry" class="input-text wc-credit-card-form-card-expiry" type="text" autocomplete="off" placeholder="MM / YY" data-openpay-card="expiration_year">
    </div>
    <div class="form-row form-row-last woocommerce-validated">
        <label for="openpay-card-cvc">Código de seguridad <span class="required">*</span></label>
        <input id="openpay-card-cvc" class="input-text wc-credit-card-form-card-cvc" type="text" autocomplete="off" placeholder="CVC" data-openpay-card="cvv2">
    </div>
        <input type="hidden" name="device_session_id" id="device_session_id" value="">
</div>
<div style="height: 1px; clear: both; border-bottom: 1px solid #CCC; margin: 10px 0 10px 0;"></div>
<div style="text-align: center">
    <img alt="" src="http://dev.bioleafy.com/wp-content/plugins/openpay-cards//assets/images/openpay.png">	
</div>		</div>
	</li>
```

En el js **openpay.js** linea **161**:
` jQuery('#openpay-holder-name').closest('p').before('<ul style="background-color: #e2401c; color: #fff;" class="woocommerce_error woocommerce-error"><li> ERROR ' + response.data.error_code + '. '+msg+'</li></ul>');`

Está buscando un ancestro _p_ del elemento _#openpay-holder-name_ para incluir el mensaje de error. Como no lo encuentra no imprime nada.

Cambiando la anterior línea por:
`jQuery('#openpay-holder-name').parent('div').prepend('<ul style="background-color: #e2401c; color: #fff;" class="woocommerce_error woocommerce-error"><li> ERROR ' + response.data.error_code + '. '+msg+'</li></ul>');`

Todo funciona perfecto. No se si este sea un caso particular de mi theme pero te lo comento por si sirve de algo.

Saludos

**Comment by fedebalderas** [comment]
Es que hay 2 tipos de validación en el plugin... El que tu mencionas es para una validación que se hace previa a enviarse al servidor, es decir, se hace una validación en JS pero únicamente valida el formato de la tarjeta, la fecha de vigencia y cosas así... esas se pintan con el código que pusiste arriba.

![screen shot 2017-05-12 at 11 02 30 am](https://cloud.githubusercontent.com/assets/5208431/26006580/93c65790-3702-11e7-9da1-6c05df8458cc.png)

Sin embargo cuando la validación ya se hace a nivel servidor, es decir, que la petición llega a Openpay y ejecuta reglas antifraude, validación de saldo con el banco, etc, ese error se pinta hasta arriba como la imagen que te mencionaba ayer.

Pero en teoría te debería de mostrar ambos mensajes de error.


Saludos!

**Comment by didi3r** [comment]
Si, los errores del back utilizan la función wc_add_notice() y con esos no hay problema, el problema eran los errores de la validación del lado del cliente. Estos últimos dependen de un markup especifico (`jQuery('#openpay-holder-name').closest('p')`) que mi theme no tiene y por eso no se mostraban. 

Se me ocurre que para mejorar la compatibilidad, agreguen un contenedor vacío exclusivo para mostrar esos errores arriba del form.
`<div id="openpay-validation-errors"></div>`

Y luego únicamente hacen referencia a él para mostrar los errores:
`jQuery('#openpay-validation-errors').html(.....)`

Así ya no dependen de que el theme tenga un markup en especial.

My two cents.
Saludos

**Comment by fedebalderas** [comment]
Lo tomaremos en cuenta, gracias.

**Comment by daniel-tinoco** [comment]
> Es que hay 2 tipos de validación en el plugin... El que tu mencionas es para una validación que se hace previa a enviarse al servidor, es decir, se hace una validación en JS pero únicamente valida el formato de la tarjeta, la fecha de vigencia y cosas así... esas se pintan con el código que pusiste arriba.
> 
> ![screen shot 2017-05-12 at 11 02 30 am](https://cloud.githubusercontent.com/assets/5208431/26006580/93c65790-3702-11e7-9da1-6c05df8458cc.png)
> 
> Sin embargo cuando la validación ya se hace a nivel servidor, es decir, que la petición llega a Openpay y ejecuta reglas antifraude, validación de saldo con el banco, etc, ese error se pinta hasta arriba como la imagen que te mencionaba ayer.
> 
> Pero en teoría te debería de mostrar ambos mensajes de error según sea el caso.
> 
> Saludos!
Oye una pregunta @fedebalderas hay forma de mostrar los mensajes de error en español o los traduces manualmente, es que vi tu formulario de open pay y vi que lo muestras en español :D

**Comment by fedebalderas** [comment]
@daniel-tinoco Si, se traducen en una función que fue diseñada con este fin:

https://github.com/open-pay/openpay-woocommerce/blob/1ce93ff89125dcd7a494962ec521aa50f9485e38/openpay-cards/openpay_cards_gateway.php#L571

No se abarcan todos, pero si los principales relacionados a las TC y los demás se dejan como genéricos.

Saludos!
