### ISSUE TITLE
ERROR 1003. La petición no pudo ser procesada.

### ISSUE THREAD

**Issue by eliacimdavila** [open-pay/openpay-woocommerce#17]
Buenas tardes.

Estoy probando en estos momentos el entorno de sandbox con las tarjetas del apartado de pruebas para que sean rechazadas:

**https://www.openpay.mx/docs/testing.html**

Sin embargo, pasa algo extraño. Cuando introduzco una de las incorrectas, por ejemplo, la **4000 0000 0000 0119**, la primera vez todo parece estar bien, y me regresa el mensaje de error **ERROR 3004. La tarjeta fue rechazada.** (aunque la página dice que debería de ser "La tarjeta ha sido identificada como una tarjeta robada.", pero ese es otro tema). Sin embargo, la segunda vez que lo intente, con esa tarjeta o con cualquier otra de las incorrectas, ya no me regresa los mensajes de error, sino siempre me regresa el mensaje: 

**ERROR 1003. La petición no pudo ser procesada.**

Pasa incluso si ingreso alguna de las tarjetas válidas. Sólo hasta que le doy refresh al checkout, ya me empieza a regresar de nuevo los mensajes de error, pero de nuevo, sólo la primera vez, y ya la segunda vez, sea válida o no, me regresa dicho mensaje.

En la consola de Chrome, cuando se hace la segunda llamada que falla, lo único que noto es que hace dos llamadas a dos urls:

**http://[siteurl]/checkout/undefined**

y

**http://[siteurl]/checkout/?wc-ajax=checkout**

Donde la primera, obviamente, marca un 404. Pero la primera vez que la llama, y sí responde bien, igual hace dicha petición y también falla, pero hace además justo después otras varias, como a:

**https://sandbox-api.openpay.mx/v1/mjovcbtcfukvhz52dbha/tokens
https://sandbox-api.openpay.mx/v1/mjovcbtcfukvhz52dbha/antifraudkeys
https://sandbox-api.openpay.mx/antifraud/mjovcbtcfukvhz52dbha/components?s=QgrTMXZweW8YMfTc6AhtO9Bz8CtWB0L9**

Y luego ya entonces la llamada a:

**http://[siteurl]/checkout/?wc-ajax=checkout**

No sé porque, al parecer, no está haciendo las llamadas la segunda vez. ¿Podrían indicarme qué podría ser o qué se debería revisar?

Gracias.

**INFORMACIÓN ADICIONAL**

Revisando los logs del Panel de Sandbox, la segunda vez que mando la llamada, cuando me marco este error, se crea el siguiente registro:

![open-pay-error3](https://user-images.githubusercontent.com/21063809/29461610-f269dc9a-83f1-11e7-9ab6-39ec0fe4ba11.JPG)

El error marcado al parecer es **"This source_id was already used"**. ¿Qué significa? ¿Hay forma de corregirlo?

Saludos.

**Comment by fedebalderas** [comment]
El caso fue cerrado vía email. El problema se debía a que el tema utilizado por la tienda reemplazaba un elemento del DOM (del checkout default de WooCommerce) que es necesario para generar el token en cada intento de pago.

**Comment by jalop123j** [comment]
Ayuda urgente por favor!!!

Hola, tengo exactamente el mismo problema en la tienda orem.com.mx.

Despues de que existe un error, las peticiones siguientes mandan el mismo source id y recibo el error:
This source_id was already used

El escenario es el mismo:

Llamada 1:

{
    "method": "card",
    "amount": 408,
    "currency": "mxn",
    "source_id": "kqlwgxgyfscaemihbn2q",
    "device_session_id": "aNkTQhVbJ3MGWNGxyiNxKa6LLMXkAJtr",
    "description": "Charge for jalop123jorem@gmail.com",
    "order_id": 8576
}

Respuesta 1:

{
    "category": "gateway",
    "description": "The card was declined",
    "http_code": 402,
    "error_code": 3001,
    "request_id": "2d903297-f6cd-42dc-95d6-36cea7945bb8"
}

Llamada 2:

{
    "method": "card",
    "amount": 408,
    "currency": "mxn",
    "source_id": "kqlwgxgyfscaemihbn2q",
    "device_session_id": "aNkTQhVbJ3MGWNGxyiNxKa6LLMXkAJtr",
    "description": "Charge for jalop123jorem@gmail.com",
    "order_id": 8577
}

Respuesta 2:

{
    "category": "request",
    "description": "This source_id was already used",
    "http_code": 422,
    "error_code": 1003,
    "request_id": "784e5064-9b0c-4cfa-9889-be0c81b9b913"
}

**Comment by kryztoval** [comment]
Seria bueno decir cuales son los temas soportados entonces?

**Comment by joneldiablo** [comment]
buen día, estoy teniendo el mismo problema, el tema que uso ya está muy avanzado para cambiarlo. qué elementos del dom son requeridos? pero mi tema es custom y no elimino nada del dom solo display:none en algunas cosas. mi sitio es llanteradelvalle.com.mx el producto de prueba es llanteradelvalle.com.mx/producto/prueba necesito hacer las pruebas de 3D secure pero no pasan por este error "ERROR 1003. La petición no pudo ser procesada.
Error en la transacción: No se pudo completar tu pago."

**Comment by joneldiablo** [comment]
al abrir las herramientas de desarrollo tengo esta consulta:   https://llanteradelvalle.com.mx/checkout/undefined 404

**Comment by iiooiio** [comment]
> El caso fue cerrado vía email. El problema se debía a que el tema utilizado por la tienda reemplazaba un elemento del DOM (del checkout default de WooCommerce) que es necesario para generar el token en cada intento de pago.

Hola, hay forma de saber cuál es ese elemento?

Gracias Federico.
