### ISSUE TITLE
Faltan los archivos js minificados de cada país dentro del plugin

### ISSUE THREAD

**Issue by TheJobGG** [open-pay/openpay-woocommerce#170]
Al descargar el plugin y agregar id y credenciales api me daba error al intentar hacer una transacción de prueba.
Viendo la consola me decía que no había sido posible obtener el archivo `mx-openpay.v1.min.js?ver=6.6.2`

Esta es una captura del contenido en `/openpay-cards/assets/js` del plugin descargado desde WordPress

![image](https://github.com/user-attachments/assets/de6be494-88a5-495f-92aa-44d206297e1e)

Y esta captura de los archivos en este repo en la misma ruta

![image](https://github.com/user-attachments/assets/4d3ab302-65f6-419e-b176-67c8787a76ac)

Solución:
Tuve que descargar el archivo js de México en mi caso desde este repo y agregarlo al plugin. Probando ahora con el archivo incluido todo fue bien.

Saludos.

**Comment by Daniel-MendezOp** [comment]
Agradecemos sus valiosas observaciones @TheJobGG

Me complace notificarle que hemos solucionado el inconveniente y a partir de este momento el plugin ya cuenta con los archivos javascript minificados en el directorio /openpay-cards/assets/js. 

¡Un cordial saludo!
