### ISSUE TITLE
No hace nada cuando se da click en pagar por el pedido

### ISSUE THREAD

**Issue by jorgeatcabo** [open-pay/openpay-woocommerce#18]
Hola, tengo un detalle con woocommerce y openpay (modo prueba), cuando creo un pedido para un cliente, y este lo quiere pagar en su cuenta, al dar click en pagar por el pedido no hace nada, me voy a la consola y hace referencia a este archivo openpay.js?ver=4.8.1 en la parte console.log("order_review");, en el dashboard de openpay no marca ningún error, tampoco en la página.
Al hacer alguna compra todo lo hace bien registrandolo en openpay, es solo con los pedidos generados para los clientes donde no ejecuta nada.

Gracias.
Saludos

**Comment by fedebalderas** [comment]
Muy probablemente sea un problema de JS, algún plugin o librería que ocupe tu tienda y que este "chocando" con el comportamiento de nuestro plugin y no esta tokenizando la tarjeta. 

¿Cuál es la URL de tu comercio para echarle un vistazo?

**Comment by jorgeatcabo** [comment]
https://www.websitesparatunegocio.com/mi-cuenta
entra con usuario el_roble2, qM&0MPdroD%hmCoBY8P$dn9T
hay una orden número 553 dale pagar y ahí vas a darte cuenta que al dar click al boton pagar pedido no hace nada. Gracias.

**Comment by fedebalderas** [comment]
@jorgeatcabo  

El formulario de tu checkout esta de la siguiente manera:
<form id="order_review" method="post">

Un formulario de una instalación de WooCommerce es así:
<form class="checkout woocommerce-checkout" name="checkout" method="post"  action="URL" enctype="multipart/form-data">

No sé si utilizan algún plugin en particular para tu checkout que modifica los atributos de la etiqueta "form" y el plugin de Openpay hace uso de las clases de la de la etiqueta para disparar ciertos eventos, es por ello que no hace nada.

De hecho en el form de tu checkout no tiene ninguna acción, cuando se tokenize la tarjeta no va a saber a donde apuntar para tramitar el cargo.

Saludos!

**Comment by jorgeatcabo** [comment]
Hola, tengo instalado el plugin gravity forms no se si afecte, lo curioso que cuando haces una compra en la tienda https://www.websitesparatunegocio.com/tienda, no en base a un pedido enviado hacia el cliente, si finaliza la compra y se registra en openpay, gracias, saludos.

**Comment by jorgeatcabo** [comment]
Hola cree una nueva instalación de wordpress con solo el woocommerce y openpay y sigue con el mismo detalle de no enviar los datos al momento de querer pagar el pedido, gracias, saludos.

**Comment by fedebalderas** [comment]
Como mencionas anteriormente, cuando se realiza el proceso normal de compra concreta el pedido, la cuestión es cuando el cliente paga en base a un pedido que tu o alguien más genero y debe entrar a pagar.

Deberías de revisar el código que genera este formulario de pago bajo pedido y en todo caso sobreescribirlo y añadirle las clases ("checkout woocommerce-checkout") que tiene el otro form (el normal), de otro modo hay que modificar el plugin de nuestro lado para que se adapte a este formulario tuyo y que es menos viable.


Saludos!

**Comment by rkgarcia** [comment]
Tengo el mismo problema en la tienda https://mibodaespaña.com @fedebalderas ¿tendrás alguna idea de qué podría ser?

He revisado y el formulario tiene las clases mencionadas en tu comentario anterior.

**Comment by fedebalderas** [comment]
@rkgarcia  Has checado la consola de tu navegador por si es que te arroja algún error?

**Comment by rkgarcia** [comment]
@fedebalderas  si, muestra lo siguiente:
order_review
woocommerce_error

**Comment by fedebalderas** [comment]
@rkgarcia  Para poder revisar esto podrías indicarme el flujo de como se realiza un pago en tu tienda? es decir, seleccionar productos/servicios y pasar al checkout. Solo vi proveedores y agregar reseñas pero nada como para "agregar a un carrito y pagar".

Saludos!

**Comment by rkgarcia** [comment]
@fedebalderas puedes ingresar a [https://mibodaespaña.com/anadir-anuncio/](https://mibodaespaña.com/anadir-anuncio/) debes crearte una cuenta después de eso ya tienes un carrito de compras y puedes intentar comprar un anuncio premium.

**Comment by rkgarcia** [comment]
¿Alguna novedad @fedebalderas ?

**Comment by rkgarcia** [comment]
@fedebalderas ¿habrá algún seguimiento de esto?
