### ISSUE TITLE
Descripción incorrecta en el al mostrar el pedido en el panel de Openpay

### ISSUE THREAD

**Issue by angelscabrerag** [open-pay/openpay-woocommerce#22]
Buen dia, tengo instalado el plugin de cobro con tarjeta y el plugin de cobro con pago en tienda en mi tienda con wordpress-woocommerce. Todo se genera correctamente, solo que al revisar la transacción en el mi panel de Openpay la descripción de la transacción muestra la leyenda:
`"Charge for micorreo@correo.com"` (el correo del usuario que realiza la orden. esto es tanto en los menus del panel tarjetas y paynet

Debería mostrar como descripción:
`"Charge for #51 Nombre del cliente" ` (el id del pedido y el nombre del cliente o el correo del cliente, pero con el Id de pedido de woocommerce).

¿Podrían solucionarlo para los 2 plugins con una actualización por favor?

**Comment by fedebalderas** [comment]
@angelscabrerag no es un cambio que tengamos programado al corto plazo ya que como tal no es un bug, sin embargo es una buena sugerencia la que haces.

Podrías realizar este cambio tu mismo modificando la función **processOpenpayCharge** del archivo **wp-content/plugins/openpay-cards/openpay_cards_gateway.php** y reemplazando el parámetro **description** por:

`"description" => sprintf("Charge for #%s %s", $this->order->get_id(), $this->order->get_billing_email()),`

**Comment by angelscabrerag** [comment]
@fedebalderas Gracias por la respuesta y por la ubicación de la linea de código, claro que la modificare. Saludos!
