### ISSUE TITLE
Call to a member function create() on null

### ISSUE THREAD

**Issue by geekfred** [open-pay/openpay-woocommerce#24]
Estimados, alguien sabe porq puede estar pasando esto al momento de querer pagar?

Fatal error: Uncaught Error: Call to a member function create() on null in /Users/geekfred/Documents/development/project.dev/wp-content/plugins/openpay-stores/openpay_stores_gateway.php:227 Stack trace: #0 /Users/geekfred/Documents/development/project.dev/wp-content/plugins/openpay-stores/openpay_stores_gateway.php(182): Openpay_Stores->createOpenpayCharge(false, Array) #1 /Users/geekfred/Documents/development/project.dev/wp-content/plugins/openpay-stores/openpay_stores_gateway.php(203): Openpay_Stores->processOpenpayCharge() #2 /Users/geekfred/Documents/development/project.dev/wp-content/plugins/woocommerce/includes/class-wc-form-handler.php(410): Openpay_Stores->process_payment(12104) #3 /Users/geekfred/Documents/development/project.dev/wp-includes/class-wp-hook.php(286): WC_Form_Handler::pay_action(Object(WP)) #4 /Users/geekfred/Documents/development/project.dev/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #5 /Users/geekfred/Documents/development/ in /Users/geekfred/Documents/development/project.dev/wp-content/plugins/openpay-stores/openpay_stores_gateway.php on line 227

Tanto el plugin como el woocommerce estan updated a la última versión.

Gracias.

**Comment by fedebalderas** [comment]
@geekfred has cambiado de modo sandbox a productivo o viceversa?

**Comment by geekfred** [comment]
Fede, negativo, todo está en modo producción.

**Comment by fedebalderas** [comment]
@geekfred Porque esto normalmente sucede cuando se realizan pruebas en modo sandbox con un usuario y después se hace el switch a modo productivo sobre la misma instalación (misma BD, por ende mismos usuarios). A los usuarios de tu plataforma se les asocia un ID de cliente de Openpay la primera vez que transaccionan, entonces al momento que trata de pagar nuevamente un usuario que se utilizó en modo sandbox, éste ID que te mencionaba no se encuentra y por eso se va como null.

**Comment by geekfred** [comment]
Entiendo, voy a probar creando otro usuario. Ahora bien, es esta la forma correcta? No deberíamos validar primero que lo que viene no sea NULL antes de realizar cualquier otra tarea? Gracias.
