### ISSUE TITLE
3d Secure not appear at checkout

### ISSUE THREAD

**Issue by giodc** [open-pay/openpay-woocommerce#26]
testing the plugin with the latest version of woocommerce. Enabled 3d secure into the plugin option, but at checkout, no 3d secure windows appear. 

Also, open-pay support say that your plugin is not compatible with woocommerce 3.5.4. can be this?

**Comment by fedebalderas** [comment]
Hi @giodc, i don't think so... it was a minor update from WooCommerce (maybe a fix), did you use this cc number 5454545454545454? 

> https://www.openpay.mx/docs/testing.html

So, if the 3D secure page doesn't show, what are you getting instead? An error?

**Comment by giodc** [comment]
Hi There, we have no error on checkout, but instead of asking for 3d code (yes, we tried all the cc number you have in your testing page) it process the transaction directly without asking any code.
Openpay validation told us that the 3d secure is mandatory to get authorized. Also, they said that our woocommerce version is not compatible with your plugin, so we need to “install” woocommerce 3.4.3 that , is obviously impossible to do because we have already upgraded our system to wordpress 5.0 and that version, is not compatible with Wp.

Thanks.

Best

Giovanni

**Comment by fedebalderas** [comment]
A few questions:

- Do you have installed version 1.5.0 of our plugin?
- Do you have your store online? Which is the URL?

**Comment by giodc** [comment]
yes, version 1.5.0 installed, 

here the url of one product, you have the add to cart form on the right, and connected with openpay test api: 

https://www.karmatrails.com/holiday/openpay/

woocommerce version: 3.5.4

**Comment by fedebalderas** [comment]
@giodc, can you share with me a screenshot of your logs (request and response) from Openpay?

**Comment by giodc** [comment]
@fedebalderas, here the screenshot, thanks 

![screen shot 2019-02-18 at 1 07 57 pm](https://user-images.githubusercontent.com/2741044/52971882-ac3bb200-337e-11e9-9a00-59e687f6eb15.png)

**Comment by fedebalderas** [comment]
I'm referring to your logs from Openpay... you can find them in your Openpay dashboard. I need them to check what parameters your store are sending.

<img width="1450" alt="captura de pantalla 2019-02-18 a la s 13 29 14" src="https://user-images.githubusercontent.com/5208431/52972735-69c7a480-3381-11e9-9cde-90c00ad95891.png">

**Comment by giodc** [comment]
Sorry Federico, here the screenshot from openpay logs:

**Comment by giodc** [comment]
i forgot the attachment, here the logs:

![screen shot 2019-02-18 at 1 34 45 pm](https://user-images.githubusercontent.com/2741044/52974821-93d09500-3388-11e9-8789-6e8f7c407648.png)

Thanks

**Comment by fedebalderas** [comment]
@giodc We update the plugin (v1.5.1), can you take a look?

**Comment by giodc** [comment]
@fedebalderas let me try, thanks!

**Comment by giodc** [comment]
@fedebalderas  now is working as expected!

![screen shot 2019-02-19 at 9 48 32 am](https://user-images.githubusercontent.com/2741044/53028064-c4b5d600-342b-11e9-8236-ab55f54c1944.png)

i have updated the plugin manually, in wordpress backend it say version 1.5.0, but is working, thanks

**Comment by fedebalderas** [comment]
@giodc I'm glad to hear that.. if something shows up let me know.
