### ISSUE TITLE
Cargo se queda en espera

### ISSUE THREAD

**Issue by jalop123j** [open-pay/openpay-woocommerce#28]
Hola, el dia de ayer actualice el plugin a la version Versión 1.5.0 

La configuración no la he cambiado, esta como siempre para realizar el cargo inmediato (Ver imagen de abajo). Ayer probé ingresando los datos de una tarjeta con datos erroneos en producción, la transacción fue rechazada pero noté que el pedido se cambia a en espera (Antes no lo hacia) y aparece esto: Pre-autorización El pedido ha cambiado de Pendiente de pago a En espera.

Hoy recibí pedido de un cliente, el pedido se quedo en espera y aparece el mensaje en la orden de woocommerce: Openpay Cards payment pre-authorized with Transaction Id of 
:
Al entrar a  Openpay, el pedido de mi cliente aparecia como pendiente, tuve que presionar la opcion de confirmar para que el pedido fuera autorizado. Todo parece indicar que el plugin esta realizando preautorizaciones sin que este configurado de esta forma.

![image](https://user-images.githubusercontent.com/30593787/53213722-0efbaa80-3618-11e9-8813-0daefdc3e570.png)

![image](https://user-images.githubusercontent.com/30593787/53214342-3e131b80-361a-11e9-9c23-7b32565b790c.png)

**Comment by fedebalderas** [comment]
@jalop123j Si, parece que el problema era la inicialización de ese parámetro... Se buscaba en los metadatos y al no encontrarse se tomaba como false y por eso la pre-autorización. Si bien bastaba con darle "Guardar" a la configuración para que tomará la nueva configuración era un bug, el cual ya fue resuelto. 

Una nueva versión fue liberada (1.5.2).

Saludos!
