### ISSUE TITLE
Activacion del Plugin openpay-cards inhabilita a woocommerce

### ISSUE THREAD

**Issue by MarcosPadilla22** [open-pay/openpay-woocommerce#29]
Hola 
Estoy intentado instalar el plugin openpay-cards en woocommerce versión 3.5.3 pero al activar el plugin el woocommerce se inhabilita.
tienen alguna idea del porque este pasando esto.

Datos servidor
PHP Version 7.0.33
Apache mod_rewrite (AllowOverride All)
WordPress 4.9.10
WooCommerce 3.5.3
cURL enabled 7.61.1
SSL yes

![error_server](https://user-images.githubusercontent.com/26065048/57091948-f66ed700-6ccf-11e9-8faa-266e9e30e84c.jpg)

**Comment by fedebalderas** [comment]
@MarcosPadilla22 has revisado el log de tu tienda? te recomendaría que habilites el modo de debug en tu Wordpress para saber puntualmente cual es el error y no únicamente el error 500.

**Comment by MarcosPadilla22** [comment]
Muchas gracias @fedebalderas ya logre activar el plugin con tus recomendaciones, era un problema de mi servidor.

**Comment by fedebalderas** [comment]
@MarcosPadilla22 Perfecto, cualquier cosa por acá andamos.

Saludos!
