### ISSUE TITLE
Error 1001

### ISSUE THREAD

**Issue by monastoremx** [open-pay/openpay-woocommerce#30]
No se pueden procesar pagos con tarjetas en woocommerce 3.6.4, siempre se obtiene ERROR 1001. La petición no pudo ser procesada.
Error en la transacción: No se pudo completar tu pago.

**Comment by fedebalderas** [comment]
Que tal @monastoremx, algunas preguntas al respecto para tener más contexto de lo que esta sucediendo:

- Que versión del plugin de Openpay tienes instalado?
- Te arroja algún error en la consola de tu navegador desde el checkout? Si es así podrías compartirnos un pantallazo.
- Se esta tokenizando la tarjeta?
- Podrías revisar los logs en tu dashboard de Openpay para saber si esta llegando alguna petición y en caso de que si, podrías revisar su detalle y compartirlo.
- Tienes tu tienda en línea para echarle un vistazo? Sería de utilidad.

**Comment by monastoremx** [comment]
Hola:

Tengo la versión 1.5.2
Tengo habilitada la opción de 3d secure
mi tienda esta en línea es www.monastore.com.mx.
Adjunto screenshoots de la consola del navegador y del log en el dashboard de openpay
![Captura de Pantalla 2019-05-30 a la(s) 18 03 00](https://user-images.githubusercontent.com/37988742/58670703-9f2b4900-8305-11e9-957f-6ecd8325a15e.png)
![Captura de Pantalla 2019-05-30 a la(s) 18 04 15](https://user-images.githubusercontent.com/37988742/58670704-9f2b4900-8305-11e9-8273-a93a6c36d86a.png)

**Comment by fedebalderas** [comment]
Es un tema del JS, pareciera que no esa reconociendo jQuery ni tampoco el método "cardNumberInput()" que es el que le da formato de separar los números de la TC de 4 en 4. 

Como el JS truena lo demás deja de funcionar, es decir, ya no tokeniza y como puedes ver en la petición el "source_id" va como null (ahí debería de ir el token).

Solo para probar, podrías buscar el siguiente archivo en tu proyecto:
https://github.com/open-pay/openpay-woocommerce/blob/master/openpay-cards/assets/js/openpay.js

- Comentar la línea 68
- Descomentar la 67
- Refrescar tu checkout y ver si ya no arroja ningún error
- Si no arroja ningún error tratar de completar la prueba y si arroja error deja tanto la línea 67 y 68 comentadas.

Me cuenta como te fue.

**Comment by monastoremx** [comment]
Me sigue arrojando el mismo error, ya deje comentadas ambas

**Comment by fedebalderas** [comment]
Si dejas ambas comentadas te sigue arrojando el error de jQuery is not defined?

**Comment by monastoremx** [comment]
sí

**Comment by monastoremx** [comment]
Creo haber encontrado que un plugin (autoptimize) cuya función es optimizar el uso de JS estaba interfiriendo con openpay, al desactivar el plugin el pago se pudo procesar sin problema.

**Comment by fedebalderas** [comment]
@monastoremx perfecto... en ese caso si pudieras volver a dejar la línea 68 descomentada como estaba originalmente y comentar la 67 porfa.

**Comment by TheKingTauro** [comment]
Hola, tengo el mismo problema:
![image](https://user-images.githubusercontent.com/60118428/72763114-cf329f80-3ba7-11ea-8ad8-680d6e775552.png)
No me deja realizar el pago, utilizo el modo de prueba (sandbox).
Introduzco los datos de la tarjeta correctamente, como lo dice la documentacion de OpenPay.
Me da el siguiente mensaje:
ERROR 1001. La petición no pudo ser procesada.
Error en la transacción: No se pudo completar tu pago. 

Ayuda, plz :c
