### ISSUE TITLE
versiones en WP mas actualizadas

### ISSUE THREAD

**Issue by rockdrigo** [open-pay/openpay-woocommerce#34]
en el sitio de WP https://profiles.wordpress.org/openpay/#content-plugins hay versiones mas actualizadas que las publicadas en el sitio de desarrollo de openpay   (  https://openpay.mx/docs/plugins/woocommerce.html   )  quiero saber si esos repositorios de WP son actualizados y mantenidos por ustedes y puedo usarlos sin ningun riesgo, o si mejor me quedo con las versiones que descargo del sitio de desarrollo de openpay

**Comment by fedebalderas** [comment]
Que onda @rockdrigo, el tema es que la documentación de la página de Openpay no esta actualizada, en breve se estará actualizando la página para que tenga la información a la par de las tiendas y repositorios, pero si los plugins de aquí https://profiles.wordpress.org/openpay/#content-plugins son mantenidos por nosotros.

Saludos!
