### ISSUE TITLE
[pregunta] cobrar porcentaje extra si seleccionan pagar a meses

### ISSUE THREAD

**Issue by joneldiablo** [open-pay/openpay-woocommerce#37]
hola, quisiera saber cómo se podría cargar el porcentaje de openpay al usuario si solicita pagar a meses, gracias. Tengo entendido que cobran el 5% de la transacción para ofrecer pagar a meses, quisiera pasar ese costo directo al cleinte, ya no serían meses sin intereses XD hahahaha, meses con intereses mci....

**Comment by fedebalderas** [comment]
@joneldiablo ahí lo que tendrías que hacer es modificar el proceso del checkout de WooCommerce como tal y no de Openpay, al final a Openpay se le pasa el monto final a cargar en la tarjeta, por ende ese cálculo lo tendrías que generar tu para también "pintarlo" en el resumen de pago de cliente (donde se desglosan los cargos, descuentos, impuestos, etc.).

**Comment by joneldiablo** [comment]
ah ya, gracias. una pregunta más, ya abusando XD
qué filter o action de woocommerce tengo que utilizar para agregar el cargo antes de procesar el pago, me imagino que tiene que ser alguno que se ejecute después al dar click en "realizar el pedido"/cobrar/procreder con la compra
