### ISSUE TITLE
ERROR 1003La petición no pudo ser procesada. Error en la transacción: No se pudo completar tu pago.

### ISSUE THREAD

**Issue by vazquezcamp** [open-pay/openpay-woocommerce#39]
Estoy en modo producción y no permite realizar los pagos con tarjeta. Cuando estoy en modo sandbox si se realiza correctamente.
![image](https://user-images.githubusercontent.com/56770616/78184197-51e89e00-7426-11ea-9e1f-b63462d85020.png)

**Comment by jose-openpay** [comment]
@vazquezcamp puede hacer el flujo de pago con un usuario nuevo, es decir, un usuario diferente al que utilizó para realizar las pruebas en modo sandbox?

**Comment by JGTI** [comment]
Te dejo la solución 
remplaza este archivo en /wp-content/plugins/openpay-cards/openpay_cards_gateway.php 
https://github.com/JGTI/openpay-wordpress-solucion/blob/main/openpay_cards_gateway.php
