### ISSUE TITLE
Undefined variable: order_id 

### ISSUE THREAD

**Issue by noubodi** [open-pay/openpay-woocommerce#4]
I keep getting this : Undefined variable: order_id in ../wordpress/wp-content/plugins/woocommerce-openpay/woocommerce-openpay.php on line 75

**Comment by fedebalderas** [comment]
Problema de la versión "Todo en uno", la cual ya no cuenta con soporte. Una nueva versión con las formas de pago en forma individual fue liberada.

**Comment by Delgesh** [comment]
You must define order_id before and the best way to do this is by using if statement isset see example : 
global $woocommerce;

	if (isset ($order_id)) {
		$order = new WC_Order($order_id);
		$items = $order->get_items();
		foreach ($items as $item) {
			$product_id = $item['product_id'];
			if ($product_id ==  your product id) {
				//do something
			} else {
				//do something
			}

		}
	}
