### ISSUE TITLE
"description": "Invalid port: 80, valid ports: 443, 8443 and 10443",

### ISSUE THREAD

**Issue by dpeligro** [open-pay/openpay-woocommerce#40]
Estoy usando actualmente Woocommerce y al instalar los plugins de PayNet y Spei, pongo mis claves y ID y me manda este error en los logs del dashboard de sandbox.
Tengo que modificar algo de los plugins?
Gracias

**Comment by jose-openpay** [comment]
@dpeligro Ambos plugins registran un Webhook de manera automática para recibir notificaciones por parte de Openpay. Para que un webhook sea válido debe tener las siguientes características: 
* Endpoint: Solo dominios (No IPs). ejemplo: https://notifications.merchant.com 
* Puerto: 443/TCP, 1518/TCP, 1519/TCP, 8443/TCP y 10443/TCP 
* Protocolo: HTTPS/TLS_1.2 
* Certificado: Válido (firmado por CA pública y match con dominio). 
Este error es mostrado cuando se utilizan ambientes locales, para que Openpay valide el webhook de manera correcta su ambiente debe estar publicado en línea. 
Saludos !
