### ISSUE TITLE
Al pagar, redirije y vuelve a solicitar los datos de la tarjeta

### ISSUE THREAD

**Issue by m1k3lm** [open-pay/openpay-woocommerce#41]
Tras rellenar los datos de tarjeta en WooCommerce y pulsar en finalizar pedido, redirije a https://sandbox-api.openpay.mx/v1/YYYYYYYY/charges/XXXXXXXX/card_capture donde se vuelven a pedir los datos de la tarjeta. 

Si se vuelven a meter los datos de la tarjeta de pruebas, el pago se acepta pero no se redirje de nuevo al comercio.

**Comment by jose-openpay** [comment]
@m1k3lm Buen día, nos podrías compartir más información sobre el error presentado:

- Versión de WooCommerce que esta utilizando
- Versión de nuestro plugin de pago con tarjeta
- La url del comercio, para echar un vistazo al flujo de pago y posibles errores en consola. 

Esto nos ayudará a tener contexto del error y encontrar una solución puntual. 

Saludos !

**Comment by m1k3lm** [comment]
No, no da error pero redirije a esa página que y vuelve a pedir el número de tarjeta.

Está con la última versión de WordPress + WooCommerce y la versión más reciente del repositorio. Te puedo pasar la url en privado

**Comment by jose-openpay** [comment]
@m1k3lm puedes compartir esta información al área de soporte Openpay, te comparto su correo electrónico soporte@openpay.mx
