### ISSUE TITLE
400 Bad Request Please specify card info

### ISSUE THREAD

**Issue by jalop123j** [open-pay/openpay-woocommerce#46]
Hi, may I know in what scenarios below error happens? I do not see the request with the card information

Example:
Request 1:

{
    "name": "XXXX",
    "last_name": "XXX",
    "email": "XXXX@gmail.com",
    "requires_account": false,
    "phone_number": "XXXXXXXX",
    "address": {
        "line1": "Av L\u00f3pXXXX",
        "line2": "La calma,",
        "line3": "",
        "state": "JA",
        "city": "Zapopan, Guadalajara",
        "postal_code": "XXXXX",
        "country_code": "MX"
    }
}

Request 2 - Source Id and device session id are empty, not sure if this causes the error

{
    "method": "card",
    "amount": "493.00",
    "currency": "mxn",
    **"source_id": null,
    "device_session_id": "",**
    "description": "Items: ConMIgo | Diario de gratitud",
    "order_id": 201139,
    "use_card_points": "false",
    "capture": true
}

RESPONSE:
{
    "http_code": 400,
    "error_code": 1001,
    "category": "request",
    "description": "Please specify card info",
    "request_id": "dc789a76-99b8-4431-9844-bf975570f046"
}

**Comment by jalop123j** [comment]
Adicionalmente estoy viendo algunos errores relacionados a la longitud del campo: 
address.line2 la longitud tiene que estar entre 0 y 50

Podrían orientarme donde obtener el tamaño máximo para cada uno de los campos.

**Comment by jose-openpay** [comment]
Good day @jalop123j,

The cards plugin uses two JQuery Openpay libraries, one generates the source_id (card tokenization) the other generates the device_session_id (client device information for Openpay's anti-fraud system). This is what I can see in your comments, the API rejects the request for these two fields.

* Can you show screenshots of your browser's console errors to find out more about the problem?
* If possible, could you share the url of your online store with us?

I share official documentation where you will find information that you are requesting:
https://openpay.mx/docs/api/#crear-un-nuevo-cliente
