### ISSUE TITLE
ERROR 1003. La petición no pudo ser procesada. Error en la transacción: No se pudo completar tu pago. modo sandbox

### ISSUE THREAD

**Issue by ilsefr** [open-pay/openpay-woocommerce#48]
Estoy usando una cuenta de sandbox para hacer pruebas y me da el error 

"ERROR 1003. La petición no pudo ser procesada.
Error en la transacción: No se pudo completar tu pago." 

intenté creando otra cuenta y usando diferentes claves y si paso la prueba y pude realizar mi pedido. 

Descarto que sea algo de versiones, plugins o mi plantilla por esta razon.

**Comment by jose-openpay** [comment]
Buen día @ilsefr 

Podría compartir algunos screenshots del error presentado al siguiente correo: soporte@openpay.mx, para dar seguimiento a su caso y detectar el problema que está presentando. También nos ayudaría que comparta la versión que está utilizando de nuestros plugins y la versión de su WooCommerce. 

Cualquier duda o comentario, quedo atento. Saludos !
