### ISSUE TITLE
 "order" is no longer used to pass an order ID

### ISSUE THREAD

**Issue by noubodi** [open-pay/openpay-woocommerce#5]
Notice: WC_Shortcode_Checkout->output fue llamado con un argumento que está obsoleto desde la versión 2.1! "order" is no longer used to pass an order ID. Use the order-pay or order-received endpoint instead. in ../wordpress/wp-includes/functions.php on line 3495

**Comment by fedebalderas** [comment]
Problema de la versión "Todo en uno", la cual ya no cuenta con soporte. Una nueva versión con las formas de pago en forma individual fue liberada.
