### ISSUE TITLE
"openpay_code_private" option not being saved in DB when using WooCommerce 2.3

### ISSUE THREAD

**Issue by MarceloPedra** [open-pay/openpay-woocommerce#7]
Hello! We have a website in production using WC 2.1 and Openpay works well. But in our sandbox with WC 2.3 we cannot validate the webhook because after analyzing how the plugin works, I see that the option **openpay_code_private** is not being saved in the DB under WooCommerce 2.3.
That option is being saved within woocommerce-openpay.php, line 412. Maybe the value being sent is incomplete, incorrect, or not sanitized, or maybe some lines above that, you are using some deprecated WooCommerce methods.
Any ideas? Can you check it out please?

Thanks in advance.

**Comment by fedebalderas** [comment]
Problema de la versión "Todo en uno", la cual ya no cuenta con soporte. Una nueva versión con las formas de pago en forma individual fue liberada.
