### ISSUE TITLE
There's no response URL

### ISSUE THREAD

**Issue by raulgonzales665** [open-pay/openpay-woocommerce#8]
I'm on wordpress 4.3.1
woocommerce 2.4.7

I try to follow your instructions up to this point:

Enter the "Response URL", "Response URL" is in Woocommerce Openpay settings.

There's no "response url" in the woocommerce openpay settings!
This is both in openpay stores and in openpay cards

Image as example.

I can't take any orders like this, I get the message INTERNAL SERVER ERRO every time a purchase is made using openpay.

![openpay](https://cloud.githubusercontent.com/assets/15116704/10473122/203031d8-71ed-11e5-8734-64bb40cd2d76.png)

**Comment by fedebalderas** [comment]
Que tal Raúl, te comento que las instrucciones de instalación no estan actualizadas. únicamente tienes que ingresar tus credenciales de sandbox (para hacer pruebas) y posteriormente ya realizar los cargos.
Podrías proporcionarme la URL de tu sitio de prueba para verificar el error INTERNAL SERVER ERROR que mencionas.

Saludos!

**Comment by eduardovkb** [comment]
Hola,

Tengo un problema similar ya que en mi caso con la ultima version de Woocomerce si aparece el campo woocomerce pero ashi me aparece una URL que no se puede modificar, que hay que hacer.

La URL es: http://www.yourpcsquad.com/?wc-api=wc_openpay

Gracias.

**Comment by fedebalderas** [comment]
Creo que estas descargando una versión antigua, ya que en la última versión de los plugins no viene ese parámetro de configuración, la pantalla que deberías de ver es como la que a continuación adjunto.
Esta URL que mencionas antes se utilizaba para el webhook y ahora es generada automáticamente, por eso mismo se removió ya que tu no deberías de hacer nada.
![screen shot 2016-03-09 at 6 11 23 pm](https://cloud.githubusercontent.com/assets/5208431/13655085/77a8d042-e622-11e5-8f2a-9f61a9251584.png)
