### ISSUE TITLE
Missing +

### ISSUE THREAD

**Issue by idelangel** [open-pay/openpay-woocommerce#83]
Hola podrian corregir esta concatenacion.

Gracias,

https://github.com/open-pay/openpay-woocommerce/blob/9ce674ba47e86a2b8a69a8f4d07e489d79de2f51/openpay-cards/openpay_cards.php#L62

**Comment by jose-openpay** [comment]
Buen día @idelangel 

Se ha subido la corrección detectada. 

Agradecemos tus comentarios, Equipo Openpay !
