### ISSUE TITLE
Erro al instalar pluggin

### ISSUE THREAD

**Issue by rodrigo01** [open-pay/openpay-woocommerce#9]
En el tutorial marcan que tengo que acceder a https://github.com/open-pay/openpay-woocommerce/master/bin , para poder descargar la version estable, pero no se encuentra nada en ese enlace, tambien trato de descargar el master completo e instarlo pero me dice que no es posible instalarlo en wordpress, podrian ayudarme ?

**Comment by fedebalderas** [comment]
Que tal Rodrigo, la cuestión es que no se han actualizado las instrucciones y el código como tal cambio demasiado.
Basta con que coloques las carpetas  openpay-cards y openpay-stores en la de plugins, o bien si haces la instalación con su instalador (importar plugin) utilizas los ZIP, de ahí en más solo es colocar las credenciales de tu cuenta de Openpay donde deben de ir y listo.

Cualquier cosa nos dices.

![open-pay openpay-woocommerce 2015-10-19 10-12-30](https://cloud.githubusercontent.com/assets/5208431/10581805/2a8aa30a-764a-11e5-8b38-0a967224c024.png)
